// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCReNbgIBMPpEnVqLlApBK_m98dx3e_5-A',
    appId: '1:634400205523:web:61253c1b39b77fb805c226',
    messagingSenderId: '634400205523',
    projectId: 'giuaki-21it164',
    authDomain: 'giuaki-21it164.firebaseapp.com',
    storageBucket: 'giuaki-21it164.appspot.com',
    measurementId: 'G-EFMGJ7G4Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJpERmHwZoONHzpfg1CQp0TkNLQ-VZHw',
    appId: '1:634400205523:android:2f6eba55ccdd32ce05c226',
    messagingSenderId: '634400205523',
    projectId: 'giuaki-21it164',
    storageBucket: 'giuaki-21it164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0E51egbqPEcuXLviMfVnrufXtOTRvkoI',
    appId: '1:634400205523:ios:208acb160e16754a05c226',
    messagingSenderId: '634400205523',
    projectId: 'giuaki-21it164',
    storageBucket: 'giuaki-21it164.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseGiuaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0E51egbqPEcuXLviMfVnrufXtOTRvkoI',
    appId: '1:634400205523:ios:208acb160e16754a05c226',
    messagingSenderId: '634400205523',
    projectId: 'giuaki-21it164',
    storageBucket: 'giuaki-21it164.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseGiuaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCReNbgIBMPpEnVqLlApBK_m98dx3e_5-A',
    appId: '1:634400205523:web:6f7e24b98247569805c226',
    messagingSenderId: '634400205523',
    projectId: 'giuaki-21it164',
    authDomain: 'giuaki-21it164.firebaseapp.com',
    storageBucket: 'giuaki-21it164.appspot.com',
    measurementId: 'G-TD0HW3M58W',
  );
}
